apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: bankist-app-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
    # Optionally, specify a NodePort value (or let Kubernetes assign one)
    # nodePort: 30000
  type: NodePort
