apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  selector:
    app: bankist-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
